services:
  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "2222:22"
    volumes:
      - sftp_data:/home/equipo/shared
    command: equipo:password:1001

volumes:
  sftp_data: